### ISSUE TITLE
install cannot continue past the installer-type screen

### ISSUE THREAD

**Issue by fossfreedom** [canonical/ubuntu-flavor-installer#10]
Having built and installed our flavour installer (https://github.com/ubuntubudgie/ubuntu-budgie-installer) the installer cannot progress beyond the installer type screen on our lunar live session (daily build iso)

Quite a few subquity type errors in the terminal I noticed.

Also attached are the terminal logs and the installer logs
[terminaloutput.txt](https://github.com/canonical/ubuntu-flavor-installer/files/10880208/terminaloutput.txt)
[installerlogs.tar.gz](https://github.com/canonical/ubuntu-flavor-installer/files/10880222/installerlogs.tar.gz)

**Comment by jpnurmi** [comment]
```
flutter: ERROR ubuntu-flavor-installer: Unhandled exception
	SubiquityException: setInputSource({"layout":"us","variant":"","toggle":null}) returned error 500
Traceback (most recent call last):
  File "/snap/ubuntu-flavor-installer/x1/bin/subiquity/subiquity/common/api/server.py", line 134, in handler
    result = await implementation(**args)
  File "/snap/ubuntu-flavor-installer/x1/bin/subiquity/subiquity/server/controllers/keyboard.py", line 247, in input_source_POST
    await self.set_input_source(data.layout, data.variant, user=user)
  File "/snap/ubuntu-flavor-installer/x1/bin/subiquity/subiquity/server/controllers/keyboard.py", line 255, in set_input_source
    await self._run_gui_command(gsettings, **kwargs)
  File "/snap/ubuntu-flavor-installer/x1/bin/subiquity/subiquity/server/controllers/keyboard.py", line 263, in _run_gui_command
    passwd = pwd.getpwnam(user if user else default_desktop_user)
KeyError: "getpwnam(): name not found: 'ubuntu'"

#0      SubiquityClient._receive (package:subiquity_client/src/client.dart:73)
<asynchronous suspension>
#1      SubiquityClient.setInputSource (package:subiquity_client/src/client.dart:162)
<asynchronous suspension>
```
Looks like we need to pass the appropriate username from the GUI to subiquity because subiquity doesn't know it as it runs as root. Not that it matters because we'll just pass `$USERNAME` but what's live session username on Ubuntu Budgie, btw? Is it specified in `/etc/casper.conf`?
```
ubuntu@ubuntu:~$ cat /etc/casper.conf 
# This file should go in /etc/casper.conf
# Supported variables are:
# USERNAME, USERFULLNAME, HOST, BUILD_SYSTEM, FLAVOUR

export USERNAME="ubuntu"
export USERFULLNAME="Live session user"
export HOST="ubuntu"
export BUILD_SYSTEM="Ubuntu"

# USERNAME and HOSTNAME as specified above won't be honoured and will be set to
# flavour string acquired at boot time, unless you set FLAVOUR to any
# non-empty string.

# export FLAVOUR="Ubuntu"
export LAYERFS_PATH="minimal.standard.live.squashfs"
```

**Comment by fossfreedom** [comment]
If you are referring to the login name - its "ubuntu-budgie"

so in /etc/casper.conf the diff is

export USERNAME="ubuntu-budgie"
export HOST="ubuntu-budgie"
we don't have the final line "export LAYERFS_PATH" in our casper.conf

**Comment by jpnurmi** [comment]
Let's give it a try again when you have time and see if we get any further with the updates and fixes that were included in:

- https://github.com/UbuntuBudgie/ubuntu-budgie-installer/pull/1

P.S. Which image are you using for testing? Do you have a 23.04-based daily-live something alike?

**Comment by fossfreedom** [comment]
@jpnurmi many thanks for the PRs

So after pulling those in and doing a fresh rebuild of the snap unfortunately the same issue occurs for the newly renamed snap

[installlogs.tar.gz](https://github.com/canonical/ubuntu-flavor-installer/files/10888156/installlogs.tar.gz)
[terminaloutput.txt](https://github.com/canonical/ubuntu-flavor-installer/files/10888157/terminaloutput.txt)

Yes - our lunar daily is here http://cdimage.ubuntu.com/ubuntu-budgie/daily-live/current/ and I'm running the snap in the live session

**Comment by jpnurmi** [comment]
Ok, thanks!

Is it possible to have `cloud-init` on the image? I found this in `/var/log/installer/subiquity-server-debug.log`:
```
2023-03-04 11:20:03,983 DEBUG subiquitycore.utils:93 arun_command called: ['cloud-init', 'status', '--wait']
2023-03-04 11:20:04,003 ERROR subiquity.server.server:422 top level error
Traceback (most recent call last):
  File "/snap/ubuntu-budgie-installer/x1/bin/subiquity/subiquity/server/server.py", line 640, in start
    await self.wait_for_cloudinit()
  File "/snap/ubuntu-budgie-installer/x1/bin/subiquity/subiquity/server/server.py", line 524, in wait_for_cloudinit
    status_cp = await asyncio.wait_for(status_coro, 600)
  File "/snap/ubuntu-budgie-installer/x1/usr/lib/python3.8/asyncio/tasks.py", line 494, in wait_for
    return fut.result()
  File "/snap/ubuntu-budgie-installer/x1/bin/subiquity/subiquitycore/utils.py", line 94, in arun_command
    proc = await asyncio.create_subprocess_exec(
  File "/snap/ubuntu-budgie-installer/x1/usr/lib/python3.8/asyncio/subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/snap/ubuntu-budgie-installer/x1/usr/lib/python3.8/asyncio/base_events.py", line 1630, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/snap/ubuntu-budgie-installer/x1/usr/lib/python3.8/asyncio/unix_events.py", line 197, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
  File "/snap/ubuntu-budgie-installer/x1/usr/lib/python3.8/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/snap/ubuntu-budgie-installer/x1/usr/lib/python3.8/asyncio/unix_events.py", line 789, in _start
    self._proc = subprocess.Popen(
  File "/snap/ubuntu-budgie-installer/x1/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/snap/ubuntu-budgie-installer/x1/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'cloud-init'
```

**Comment by fossfreedom** [comment]
I certainly can add it to the live seed - I did a manual `sudo apt install cloud-init` to the live session and reran but the same results. grep for cloud in /var/log/installer showed that new installer logs were created but the "no such file or directory: cloud-init" was still generated.

Is there something else that I need to-do to kick cloud-init into life?  BTW - what is cloud-init?

**Comment by jpnurmi** [comment]
It'll probably help to restart Subiquity after installing cloud-init because Subiquity waits on it on startup.

My keyboard screen fix wasn't 100% correct because I wrongly assumed the variables in `/etc/casper.conf` to be in the environment. It turns out we need to pass `env['USER']` instead of `env['USERNAME']` to tell Subiquity the correct live session username for changing the keyboard. Anyway, keyboard layout screen already works if you start the GUI in an environment that has `USERNAME=ubuntu-budgie` set. :)

Once you reach the actual installation, however, then we get into the more interesting parts...

```
Mar 04 13:08:42 ubuntu-budgie subiquity_log.7875[8491]: mount: /tmp/tmpyb83mmkh/mount: special device overlay does not exist.
Mar 04 13:08:42 ubuntu-budgie subiquity_log.7875[8491]:        dmesg(1) may have more information after failed mount system call.
Mar 04 13:08:45 ubuntu-budgie subiquity_log.7875[8512]: mount: /tmp/tmp243hg29o/mount: special device overlay does not exist.
Mar 04 13:08:45 ubuntu-budgie subiquity_log.7875[8512]:        dmesg(1) may have more information after failed mount system call.
```

**Comment by fossfreedom** [comment]
ah - excellent - making progress.  So now I can get through the installer-type screen and onto the slides. Here I see that the installer failed message in red.

[installer.tar.gz](https://github.com/canonical/ubuntu-flavor-installer/files/10888426/installer.tar.gz)
[terminaloutput.txt](https://github.com/canonical/ubuntu-flavor-installer/files/10888427/terminaloutput.txt)

**Comment by jpnurmi** [comment]
We're reaching areas where I have very little knowledge but does [livecd-rootfs](https://git.launchpad.net/livecd-rootfs) ring any bells to you? There are some differences between the old environment for Ubiquity and what Subiquity needs.

**Comment by fossfreedom** [comment]
Ah. 'fraid that isn't an area I am familiar with ... just know the name but that's it.

**Comment by jpnurmi** [comment]
https://git.launchpad.net/livecd-rootfs/tree/live-build/auto/config

Budgie looks like this:
```
	ubuntu-budgie)
		add_task install minimal standard ubuntu-budgie-desktop
		LIVE_TASK='ubuntu-budgie-live'
		;;
```

The "legacy" Ubuntu build looks similar:
```
			legacy)
				LIVE_TASK='ubuntu-live'
				add_task install minimal standard ubuntu-desktop
				add_task live ubuntu-desktop-minimal-default-languages ubuntu-desktop-default-languages
				KERNEL_FLAVOURS='generic-hwe-22.04'
				if [ "$SUBARCH" = "intel-iot" ]; then
					KERNEL_FLAVOURS='image-intel'
				fi
				;;
```

vs.

The new live session looks pretty different:
```
			*)
				touch config/universe-enabled
				PASSES_TO_LAYERS="true"
				KERNEL_FLAVOURS='generic-hwe-22.04'
				add_task minimal minimal standard ubuntu-desktop-minimal ubuntu-desktop-minimal-default-languages
				add_task minimal.standard ubuntu-desktop ubuntu-desktop-default-languages
				add_task minimal.standard.live ubuntu-live
				add_package minimal cloud-init
				remove_package minimal.standard.live ubiquity-frontend-gtk
				add_snap minimal.standard.live ubuntu-desktop-installer/classic

				seeded_langs="$(get_seeded_languages desktop-minimal desktop)"
				echo "$seeded_langs" | tr ' ' ',' > config/seeded-languages
				derive_language_layers minimal desktop-minimal desktop-minimal-default-languages "$seeded_langs"
				derive_language_layers minimal.standard desktop desktop-default-languages "$seeded_langs"
				cat <<-EOF > config/minimal.catalog-in.yaml
					name: "Ubuntu Desktop (minimized)"
					description: >-
					  A minimal but usable Ubuntu Desktop.
					id: ubuntu-desktop-minimal
					type: fsimage-layered
					variant: desktop
					locale_support: langpack
				EOF
				cat <<-EOF > config/minimal.standard.catalog-in.yaml
					name: "Ubuntu Desktop"
					description: >-
					  A full featured Ubuntu Desktop.
					id: ubuntu-desktop
					type: fsimage-layered
					variant: desktop
					locale_support: langpack
					default: yes
				EOF
				/usr/share/livecd-rootfs/checkout-translations-branch \
					https://git.launchpad.net/subiquity po config/catalog-translations
				;;
```

**Comment by fossfreedom** [comment]
We can now close this since we now have mantic dailies with the new installer.
