### ISSUE TITLE
Streamline updates

### ISSUE THREAD

**Issue by jpnurmi** [canonical/ubuntu-flavor-installer#13]
Bumping the sha1 in `pubspec_overrides.yaml` is inconvenient.

**Comment by fossfreedom** [comment]
@jpnurmi the release team will be shortly amending our (UB) iso to include our snap installer for 23.10.

Whilst this particular issue is pending - should flavours be cherry-picking each bot update (https://github.com/canonical/ubuntu-flavor-installer/pull/15) as and when there is a release - or just waiting for each pull request to be evaluated and merged ?

**Comment by jpnurmi** [comment]
New structure based on [ubuntu-desktop-provision](https://github.com/canonical/ubuntu-desktop-provision):
- https://github.com/canonical/ubuntu-flavor-installer/pull/21
