### ISSUE TITLE
stuck at preparing ubuntu budgie

### ISSUE THREAD

**Issue by fossfreedom** [canonical/ubuntu-flavor-installer#33]
![image](https://github.com/canonical/ubuntu-flavor-installer/assets/996240/52f6a056-e905-4901-8b3d-da162892e185)

Todays daily contains the latest installer.

It seems to be a bit stuck though on the first screen - the next button is not enabled and the preparing animation just circles forever.

This is a brand new virtualbox VM - standard options with the exception of 5GB ram and 25GB disk space.

Seems to be flutter permissions looking at the journal log

[output.txt](https://github.com/canonical/ubuntu-flavor-installer/files/12353207/output.txt)

**Comment by fossfreedom** [comment]
Installing the package gnome-session-canberra gets past that screen.  I presume the code is assuming that it should be able to run canberra-gtk-play for some reason?

**Comment by kenvandine** [comment]
> Installing the package gnome-session-canberra gets past that screen. I presume the code is assuming that it should be able to run canberra-gtk-play for some reason?

Ah, indeed I think it does.

**Comment by fossfreedom** [comment]
Thanks Ken - the staging now ensures the next page is seen to pick the locale.

Nicely done!  cheers.
